# Generated by Django 5.1 on 2026-01-28 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_add_level2_captain_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('level_0', 'Level 0 - Super Admin'), ('level_1', 'Level 1 - Senior Authority'), ('level_2', 'Level 2 - Field Authority'), ('level_2_captain', 'Level 2 Captain - Field Supervisor'), ('level_3', 'Level 3 - JanMitra Member')], db_index=True, default='level_3', help_text='User role determining access level', max_length=20),
        ),
    ]
