# Generated by Django 5.1 on 2026-04-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_device_token'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_stations',
            field=models.ManyToManyField(blank=True, help_text="Police stations under this user's jurisdiction (for L3 regional officers)", related_name='regional_officers', to='core.policestation'),
        ),
    ]
