# Generated by Django 5.1 on 2026-01-28 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_incident_broadcast_api'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='text_content',
        ),
        migrations.AddField(
            model_name='incident',
            name='area_name',
            field=models.CharField(blank=True, help_text='Resolved area/locality name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='city',
            field=models.CharField(blank=True, help_text='City name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='state',
            field=models.CharField(blank=True, help_text='State name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='escalation_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='case',
            name='last_escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_rejected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='solution_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='solved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='solved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cases_solved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casenote',
            name='author_level',
            field=models.CharField(help_text="Author's role level at time of note creation", max_length=10),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='User who changed the status (null for system/auto-escalation)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='case_status_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='from_level',
            field=models.IntegerField(blank=True, choices=[(2, 'Level 2 - Field Officers'), (1, 'Level 1 - Senior Officers'), (0, 'Level 0 - Highest Authority')], null=True),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='to_level',
            field=models.IntegerField(blank=True, choices=[(2, 'Level 2 - Field Officers'), (1, 'Level 1 - Senior Officers'), (0, 'Level 0 - Highest Authority')], null=True),
        ),
    ]
