# Generated by Django 5.1 on 2026-04-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_schema_corrections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='current_level',
            field=models.CharField(choices=[('L0', 'L0 - Field Officer'), ('L1', 'L1 - PSO'), ('L2', 'L2 - PI'), ('L3', 'L3 - Higher Authority'), ('L4', 'L4 - Top Authority')], db_index=True, default='L1', help_text='Current handling level (L0/L1/L2/L3/L4)', max_length=10),
        ),
        migrations.AlterField(
            model_name='case',
            name='sla_deadline',
            field=models.DateTimeField(db_index=True, help_text='Deadline for resolution before auto-escalation (48h)'),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('open', 'Open'), ('solved', 'Solved'), ('rejected', 'Rejected'), ('closed', 'Closed')], db_index=True, default='new', help_text='Current case status', max_length=20),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='from_level',
            field=models.CharField(blank=True, choices=[('L0', 'L0 - Field Officer'), ('L1', 'L1 - PSO'), ('L2', 'L2 - PI'), ('L3', 'L3 - Higher Authority'), ('L4', 'L4 - Top Authority'), (2, 'Level 2 - Field Officers (Legacy)'), (1, 'Level 1 - Senior Officers (Legacy)'), (0, 'Level 0 - Highest Authority (Legacy)')], help_text='Previous level (L0/L1/L2/L3/L4)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('open', 'Open'), ('solved', 'Solved'), ('rejected', 'Rejected'), ('closed', 'Closed')], help_text='Previous status (null for initial creation)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='to_level',
            field=models.CharField(blank=True, choices=[('L0', 'L0 - Field Officer'), ('L1', 'L1 - PSO'), ('L2', 'L2 - PI'), ('L3', 'L3 - Higher Authority'), ('L4', 'L4 - Top Authority'), (2, 'Level 2 - Field Officers (Legacy)'), (1, 'Level 1 - Senior Officers (Legacy)'), (0, 'Level 0 - Highest Authority (Legacy)')], help_text='New level (L0/L1/L2/L3/L4)', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='to_status',
            field=models.CharField(choices=[('new', 'New'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('open', 'Open'), ('solved', 'Solved'), ('rejected', 'Rejected'), ('closed', 'Closed')], help_text='New status', max_length=20),
        ),
    ]
