# Generated by Django 5.1 on 2026-04-16 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_change_casestatus_level_to_char'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='incident_location',
            field=models.CharField(default='Not specified', help_text='Manual incident location description (required)', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='category',
            field=models.CharField(choices=[('GAMBLING', 'Gambling'), ('THEFT', 'Theft'), ('WOMEN_HARASSMENT', 'Women Harassment'), ('PROPERTY_DISPUTE', 'Property Dispute'), ('TRAFFIC_ISSUE', 'Traffic Issue'), ('MISSING_PERSON', 'Missing Person'), ('ILLEGAL_ALCOHOL', 'Illegal Alcohol'), ('VEHICLE_RELATED', 'Vehicle Related'), ('HARASSMENT', 'Harassment'), ('PHYSICAL_INJURY', 'Physical Injury'), ('RTI_REQUEST', 'RTI Request'), ('LAND_DISPUTE', 'Land Dispute'), ('DOWRY', 'Dowry'), ('ANTI_SOCIAL_ACTIVITY', 'Anti-social Activity'), ('POLICE_COMPLAINT', 'Complaint Against Police'), ('SUICIDE', 'Suicide'), ('CYBER_CRIME', 'Cyber Crime'), ('LOST_PROPERTY', 'Lost/Stolen Property')], db_index=True, help_text='Incident category (required)', max_length=30),
        ),
    ]
