# Generated by Django 6.0.1 on 2026-01-21 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('report_number', models.CharField(db_index=True, help_text='Human-readable report number (e.g., JM-2024-000001)', max_length=30, unique=True)),
                ('submitted_at', models.DateTimeField(blank=True, db_index=True, help_text='When the report was submitted', null=True)),
                ('encrypted_title', models.BinaryField(help_text='AES-256-GCM encrypted title')),
                ('encrypted_content', models.BinaryField(help_text='AES-256-GCM encrypted content')),
                ('encryption_iv', models.BinaryField(help_text='Initialization vector for AES-GCM', max_length=16)),
                ('encryption_tag', models.BinaryField(help_text='Authentication tag for AES-GCM', max_length=16)),
                ('encryption_key_id', models.CharField(help_text='Identifier for the encryption key (for key rotation)', max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('received', 'Received'), ('under_review', 'Under Review'), ('pending_info', 'Pending Additional Information'), ('escalated', 'Escalated'), ('escalation_pending', 'Escalation Pending'), ('validated', 'Validated'), ('actionable', 'Actionable Intelligence'), ('action_taken', 'Action Taken'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('invalid', 'Invalid'), ('duplicate', 'Duplicate')], db_index=True, default='draft', help_text='Current report status', max_length=30)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', help_text='Report priority level', max_length=20)),
                ('category', models.CharField(choices=[('general', 'General Intelligence'), ('public_safety', 'Public Safety'), ('infrastructure', 'Infrastructure'), ('environmental', 'Environmental'), ('social', 'Social'), ('economic', 'Economic'), ('governance', 'Governance'), ('other', 'Other')], db_index=True, default='general', help_text='Report category', max_length=30)),
                ('jurisdiction_code', models.CharField(db_index=True, help_text='Jurisdiction code for routing', max_length=50)),
                ('location_zone', models.CharField(blank=True, help_text='General location zone (non-precise)', max_length=100)),
                ('incident_timestamp', models.DateTimeField(blank=True, help_text='When the reported incident occurred', null=True)),
                ('assigned_at', models.DateTimeField(blank=True, help_text='When the report was assigned', null=True)),
                ('is_escalated', models.BooleanField(db_index=True, default=False, help_text='Whether report has been escalated')),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When the report was escalated', null=True)),
                ('decryption_authorized', models.BooleanField(default=False, help_text='Whether decryption has been authorized by Level 1')),
                ('decryption_authorized_at', models.DateTimeField(blank=True, help_text='When decryption was authorized', null=True)),
                ('decryption_reason', models.TextField(blank=True, help_text='Justification for decryption authorization')),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes about report resolution (not encrypted)')),
                ('closed_at', models.DateTimeField(blank=True, help_text='When the report was closed', null=True)),
                ('media_count', models.PositiveIntegerField(default=0, help_text='Number of attached media files')),
                ('submitter_trust_score', models.PositiveSmallIntegerField(default=50, help_text="Submitter's trust score at time of submission")),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Currently assigned authority', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reports', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, help_text='Authority who closed the report', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decryption_authorized_by', models.ForeignKey(blank=True, help_text='Level 1 authority who authorized decryption', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decryption_authorizations', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(blank=True, help_text='Authority to whom report was escalated', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalated_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(help_text='JanMitra member who submitted the report', on_delete=django.db.models.deletion.PROTECT, related_name='submitted_reports', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
                'db_table': 'reports',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('content', models.TextField(help_text='Note content')),
                ('is_private', models.BooleanField(default=False, help_text='If true, only visible to same-level or higher authorities')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_notes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='reports.report')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Note',
                'verbose_name_plural': 'Report Notes',
                'db_table': 'report_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('received', 'Received'), ('under_review', 'Under Review'), ('pending_info', 'Pending Additional Information'), ('escalated', 'Escalated'), ('escalation_pending', 'Escalation Pending'), ('validated', 'Validated'), ('actionable', 'Actionable Intelligence'), ('action_taken', 'Action Taken'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('invalid', 'Invalid'), ('duplicate', 'Duplicate')], help_text='Previous status', max_length=30)),
                ('to_status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('received', 'Received'), ('under_review', 'Under Review'), ('pending_info', 'Pending Additional Information'), ('escalated', 'Escalated'), ('escalation_pending', 'Escalation Pending'), ('validated', 'Validated'), ('actionable', 'Actionable Intelligence'), ('action_taken', 'Action Taken'), ('closed', 'Closed'), ('rejected', 'Rejected'), ('invalid', 'Invalid'), ('duplicate', 'Duplicate')], help_text='New status', max_length=30)),
                ('reason', models.TextField(blank=True, help_text='Reason for status change')),
                ('changed_by', models.ForeignKey(help_text='User who changed the status', on_delete=django.db.models.deletion.PROTECT, related_name='report_status_changes', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='reports.report')),
            ],
            options={
                'verbose_name': 'Report Status History',
                'verbose_name_plural': 'Report Status Histories',
                'db_table': 'report_status_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', 'priority'], name='reports_status_53694d_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['jurisdiction_code', 'status'], name='reports_jurisdi_18fe87_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['assigned_to', 'status'], name='reports_assigne_437206_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['submitted_by', 'submitted_at'], name='reports_submitt_229b3d_idx'),
        ),
    ]
