# Generated by Django 6.0.1 on 2026-01-23 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_case_lifecycle_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='case',
            new_name='cases_status_9a5d6f_idx',
            old_name='cases_status_level_idx',
        ),
        migrations.RenameIndex(
            model_name='case',
            new_name='cases_sla_dea_cee997_idx',
            old_name='cases_sla_deadline_idx',
        ),
        migrations.RenameIndex(
            model_name='case',
            new_name='cases_current_bc36d3_idx',
            old_name='cases_level_status_sla_idx',
        ),
        migrations.AlterField(
            model_name='casestatushistory',
            name='from_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('solved', 'Solved'), ('rejected', 'Rejected'), ('closed', 'Closed')], help_text='Previous status (null for initial creation)', max_length=20, null=True),
        ),
    ]
