# Generated by Django 5.1 on 2026-01-28 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_add_deleted_at_to_incidentmedia'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='incidentmedia',
            new_name='incident_me_inciden_1e87ca_idx',
            old_name='incident_me_inciden_7f3c8a_idx',
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted'),
        ),
        migrations.AlterField(
            model_name='incidentmedia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
    ]
