# Generated by Django 6.0.1 on 2026-01-21 11:44

import django.db.models.deletion
import django.utils.timezone
import media_storage.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('encrypted_file', models.FileField(help_text='Encrypted media file', upload_to=media_storage.models.encrypted_media_path)),
                ('encrypted_thumbnail', models.FileField(blank=True, help_text='Encrypted thumbnail', null=True, upload_to='encrypted_media/thumbnails/')),
                ('encrypted_filename', models.BinaryField(blank=True, help_text='Encrypted original filename', null=True)),
                ('encryption_iv', models.BinaryField(help_text='Initialization vector for AES-GCM', max_length=16)),
                ('encryption_tag', models.BinaryField(help_text='Authentication tag for AES-GCM', max_length=16)),
                ('encryption_key_id', models.CharField(help_text='Identifier for the encryption key', max_length=64)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], db_index=True, help_text='Type of media', max_length=20)),
                ('mime_type', models.CharField(help_text='MIME type of original file', max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='Size of encrypted file in bytes')),
                ('original_size', models.PositiveIntegerField(help_text='Size of original file before encryption')),
                ('content_hash', models.CharField(db_index=True, help_text='SHA-256 hash of encrypted content', max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order within report')),
                ('is_processed', models.BooleanField(default=False, help_text='Whether media has been processed (virus scan, etc.)')),
                ('is_clean', models.BooleanField(default=True, help_text='Whether media passed security scans')),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration in seconds for audio/video', null=True)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Width in pixels', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Height in pixels', null=True)),
                ('report', models.ForeignKey(help_text='Report this media belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='reports.report')),
                ('uploaded_by', models.ForeignKey(help_text='User who uploaded this media', on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Report Media',
                'verbose_name_plural': 'Report Media',
                'db_table': 'report_media',
                'ordering': ['report', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MediaAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accessed_by_id', models.CharField(db_index=True, help_text='UUID of user who accessed (as string for immutability)', max_length=36)),
                ('accessed_by_role', models.CharField(help_text='Role at time of access', max_length=20)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('access_type', models.CharField(choices=[('view_metadata', 'View Metadata'), ('download', 'Download'), ('decrypt', 'Decrypt')], help_text='Type of access', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('was_authorized', models.BooleanField(default=True, help_text='Whether access was authorized')),
                ('authorization_id', models.CharField(blank=True, help_text='UUID of decryption authorization if applicable', max_length=36)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='media_storage.reportmedia')),
            ],
            options={
                'verbose_name': 'Media Access Log',
                'verbose_name_plural': 'Media Access Logs',
                'db_table': 'media_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='reportmedia',
            index=models.Index(fields=['report', 'media_type'], name='report_medi_report__c7a560_idx'),
        ),
        migrations.AddIndex(
            model_name='reportmedia',
            index=models.Index(fields=['content_hash'], name='report_medi_content_6bd45b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaaccesslog',
            index=models.Index(fields=['media', 'timestamp'], name='media_acces_media_i_a347eb_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaaccesslog',
            index=models.Index(fields=['accessed_by_id', 'timestamp'], name='media_acces_accesse_036893_idx'),
        ),
    ]
