# Generated by Django 6.0.1 on 2026-01-21 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecryptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('reason', models.TextField(help_text='Reason for decryption request')),
                ('legal_authority', models.CharField(blank=True, help_text='Legal authority for decryption', max_length=200)),
                ('case_reference', models.CharField(blank=True, help_text='Case/investigation reference', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('include_media', models.BooleanField(default=False, help_text='Whether to also decrypt attached media')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Report to decrypt', on_delete=django.db.models.deletion.PROTECT, related_name='decryption_requests', to='reports.report')),
                ('requested_by', models.ForeignKey(help_text='Authority requesting decryption', on_delete=django.db.models.deletion.PROTECT, related_name='decryption_requests_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='decryption_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Decryption Request',
                'verbose_name_plural': 'Decryption Requests',
                'db_table': 'decryption_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('urgent', 'Urgent'), ('immediate', 'Immediate')], default='routine', help_text='Escalation urgency', max_length=20)),
                ('reason', models.TextField(help_text='Reason for escalation')),
                ('additional_notes', models.TextField(blank=True, help_text='Additional context or notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', help_text='Current escalation status', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When escalation was resolved', null=True)),
                ('resolution_notes', models.TextField(blank=True, help_text='Notes on resolution')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('escalated_by', models.ForeignKey(help_text='Level 2 authority creating escalation', on_delete=django.db.models.deletion.PROTECT, related_name='escalations_created', to=settings.AUTH_USER_MODEL)),
                ('escalated_to', models.ForeignKey(help_text='Level 1 authority to handle escalation', on_delete=django.db.models.deletion.PROTECT, related_name='escalations_received', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(help_text='Report being escalated', on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='reports.report')),
                ('resolved_by', models.ForeignKey(blank=True, help_text='Authority who resolved the escalation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='escalations_resolved', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escalation',
                'verbose_name_plural': 'Escalations',
                'db_table': 'escalations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority'], name='escalations_status_01bc89_idx'), models.Index(fields=['escalated_to', 'status'], name='escalations_escalat_4ca478_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdentityRevealRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('justification', models.TextField(help_text='Legal and operational justification for reveal')),
                ('legal_authority', models.CharField(help_text='Legal authority/section under which reveal is requested', max_length=200)),
                ('case_reference', models.CharField(blank=True, help_text='Case/FIR/investigation reference number', max_length=100)),
                ('urgency', models.CharField(choices=[('routine', 'Routine'), ('priority', 'Priority'), ('urgent', 'Urgent'), ('immediate', 'Immediate')], default='routine', help_text='Urgency of the request', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='pending', help_text='Request status', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When request was reviewed', null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Notes from reviewer')),
                ('revealed_at', models.DateTimeField(blank=True, help_text='When identity was actually revealed', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='Optional expiry for identity access', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='User who soft-deleted this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('related_report', models.ForeignKey(blank=True, help_text='Related report if applicable', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_reveal_requests', to='reports.report')),
                ('requested_by', models.ForeignKey(help_text='Authority requesting identity reveal', on_delete=django.db.models.deletion.PROTECT, related_name='identity_reveals_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Level 1 authority who reviewed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identity_reveals_reviewed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='JanMitra member whose identity is requested', on_delete=django.db.models.deletion.PROTECT, related_name='identity_reveal_requests', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Identity Reveal Request',
                'verbose_name_plural': 'Identity Reveal Requests',
                'db_table': 'identity_reveal_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'urgency'], name='identity_re_status_c0a924_idx'), models.Index(fields=['target_user', 'status'], name='identity_re_target__ce5c14_idx')],
            },
        ),
    ]
