# Generated by Django 6.0.1 on 2026-01-21 11:44

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('identifier', models.CharField(help_text='Unique identifier (email for authorities, anonymous ID for JanMitra)', max_length=255, unique=True)),
                ('role', models.CharField(choices=[('level_1', 'Level 1 - Highest Authority'), ('level_2', 'Level 2 - Field Authority'), ('level_3', 'Level 3 - JanMitra Member')], db_index=True, default='level_3', help_text='User role determining access level', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Temporarily Suspended'), ('revoked', 'Access Revoked'), ('pending', 'Pending Activation')], db_index=True, default='pending', help_text='Current account status', max_length=20)),
                ('is_anonymous', models.BooleanField(default=False, help_text='True for JanMitra members (identity protected)')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether user can access admin site')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether user account is active')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last successful login', null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0, help_text='Count of consecutive failed login attempts')),
                ('last_failed_login', models.DateTimeField(blank=True, help_text='Timestamp of last failed login attempt', null=True)),
                ('password_changed_at', models.DateTimeField(blank=True, help_text='Timestamp when password was last changed', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, help_text='Timestamp when access was revoked', null=True)),
                ('revocation_reason', models.TextField(blank=True, help_text='Reason for revocation (audit requirement)')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('revoked_by', models.ForeignKey(blank=True, help_text="Authority who revoked this user's access", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revocations_issued', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'janmitra_users',
            },
        ),
        migrations.CreateModel(
            name='AuthorityProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('designation', models.CharField(help_text='Official designation/title', max_length=100)),
                ('department', models.CharField(help_text='Department or unit', max_length=200)),
                ('jurisdiction_code', models.CharField(db_index=True, help_text='Jurisdiction/area code', max_length=50)),
                ('jurisdiction_name', models.CharField(help_text='Human-readable jurisdiction name', max_length=200)),
                ('contact_phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number', regex='^\\+?[1-9]\\d{6,14}$')])),
                ('contact_email', models.EmailField(blank=True, help_text='Official email address', max_length=254)),
                ('reports_handled', models.PositiveIntegerField(default=0, help_text='Total reports handled')),
                ('reports_escalated', models.PositiveIntegerField(default=0, help_text='Reports escalated to higher authority')),
                ('avg_response_time_hours', models.FloatField(default=0.0, help_text='Average response time in hours')),
                ('supervisor', models.ForeignKey(blank=True, help_text='Supervising authority', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subordinates', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authority_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authority Profile',
                'verbose_name_plural': 'Authority Profiles',
                'db_table': 'authority_profiles',
            },
        ),
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('device_fingerprint_hash', models.CharField(db_index=True, help_text='SHA-256 hash of device fingerprint', max_length=64)),
                ('device_name', models.CharField(blank=True, help_text='Human-readable device name', max_length=100)),
                ('device_type', models.CharField(blank=True, help_text='Device type (phone/tablet)', max_length=50)),
                ('os_name', models.CharField(blank=True, help_text='Operating system name', max_length=50)),
                ('os_version', models.CharField(blank=True, help_text='Operating system version', max_length=20)),
                ('app_version', models.CharField(blank=True, help_text='JanMitra app version', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this session is currently active')),
                ('refresh_token_jti', models.CharField(blank=True, help_text='JWT ID of current refresh token', max_length=255)),
                ('last_activity_at', models.DateTimeField(auto_now=True, help_text='Last activity timestamp')),
                ('last_activity_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last activity', null=True)),
                ('push_token', models.CharField(blank=True, help_text='FCM/APNs token for push notifications', max_length=255)),
                ('invalidated_at', models.DateTimeField(blank=True, help_text='When session was invalidated', null=True)),
                ('invalidation_reason', models.CharField(blank=True, choices=[('NEW_DEVICE', 'New device login'), ('LOGOUT', 'User logout'), ('ACCESS_REVOKED', 'Access revoked'), ('SECURITY', 'Security invalidation'), ('EXPIRED', 'Session expired')], help_text='Reason for invalidation', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Session',
                'verbose_name_plural': 'Device Sessions',
                'db_table': 'device_sessions',
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('code', models.CharField(db_index=True, help_text='The invite code string', max_length=20, unique=True)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether code has been used')),
                ('used_at', models.DateTimeField(blank=True, help_text='When the code was used', null=True)),
                ('expires_at', models.DateTimeField(help_text='Expiration timestamp')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this invite')),
                ('max_uses', models.PositiveIntegerField(default=1, help_text='Maximum number of times code can be used')),
                ('use_count', models.PositiveIntegerField(default=0, help_text='Number of times code has been used')),
                ('issued_by', models.ForeignKey(help_text='Authority who issued this code', on_delete=django.db.models.deletion.PROTECT, related_name='invite_codes_issued', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, help_text='User who used this code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_code_used', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite Code',
                'verbose_name_plural': 'Invite Codes',
                'db_table': 'invite_codes',
            },
        ),
        migrations.CreateModel(
            name='JanMitraProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('device_fingerprint_hash', models.CharField(db_index=True, help_text='SHA-256 hash of device fingerprint', max_length=64)),
                ('total_reports_submitted', models.PositiveIntegerField(default=0, help_text='Total number of reports submitted')),
                ('verified_reports_count', models.PositiveIntegerField(default=0, help_text='Number of reports verified as credible')),
                ('rejected_reports_count', models.PositiveIntegerField(default=0, help_text='Number of reports rejected')),
                ('trust_score', models.PositiveSmallIntegerField(default=50, help_text='Trust score based on report history (0-100)')),
                ('identity_revealed', models.BooleanField(default=False, help_text='True if identity has been revealed (lawful access)')),
                ('identity_revealed_at', models.DateTimeField(blank=True, help_text='Timestamp when identity was revealed', null=True)),
                ('identity_revealed_to', models.ForeignKey(blank=True, help_text='Authority who received identity reveal', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='identities_revealed_to', to=settings.AUTH_USER_MODEL)),
                ('invite_code', models.ForeignKey(help_text='Invite code used for registration', on_delete=django.db.models.deletion.PROTECT, related_name='registered_members', to='authentication.invitecode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='janmitra_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'JanMitra Profile',
                'verbose_name_plural': 'JanMitra Profiles',
                'db_table': 'janmitra_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='janmitra_us_role_345d81_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['identifier'], name='janmitra_us_identif_a16b7a_idx'),
        ),
        migrations.AddIndex(
            model_name='authorityprofile',
            index=models.Index(fields=['jurisdiction_code'], name='authority_p_jurisdi_42df61_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['user', 'is_active'], name='device_sess_user_id_026746_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesession',
            index=models.Index(fields=['device_fingerprint_hash'], name='device_sess_device__d4194d_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['code', 'is_used'], name='invite_code_code_e4d3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='invitecode',
            index=models.Index(fields=['issued_by', 'is_used'], name='invite_code_issued__f8120f_idx'),
        ),
    ]
