# Generated by Django 6.0.1 on 2026-01-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_standardize_role_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('LEVEL_0', 'Level 0 - Highest Authority'), ('LEVEL_1', 'Level 1 - Senior Authority'), ('LEVEL_2', 'Level 2 - Field Authority'), ('LEVEL_2_CAPTAIN', 'Level 2 Captain - Field Supervisor'), ('JANMITRA', 'JanMitra Member')], db_index=True, default='JANMITRA', help_text='User role determining access level', max_length=20),
        ),
    ]
