# Generated by Django 6.0.1 on 2026-01-21 11:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityRevealLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('janmitra_user_id', models.CharField(db_index=True, help_text='UUID of JanMitra user whose identity was revealed', max_length=36)),
                ('revealed_to_user_id', models.CharField(db_index=True, help_text='UUID of authority who received the identity', max_length=36)),
                ('revealed_to_role', models.CharField(help_text='Role of authority at time of reveal', max_length=20)),
                ('approved_by_user_id', models.CharField(db_index=True, help_text='UUID of Level 1 authority who approved', max_length=36)),
                ('related_report_id', models.CharField(blank=True, help_text='UUID of related report', max_length=36)),
                ('justification', models.TextField(help_text='Legal/operational justification for reveal')),
                ('legal_authority', models.CharField(blank=True, help_text='Legal authority/section under which reveal was authorized', max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Identity Reveal Log',
                'verbose_name_plural': 'Identity Reveal Logs',
                'db_table': 'identity_reveal_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('auth.login.success', 'Login Success'), ('auth.login.failed', 'Login Failed'), ('auth.logout', 'Logout'), ('auth.token.refresh', 'Token Refresh'), ('auth.token.revoked', 'Token Revoked'), ('auth.password.changed', 'Password Changed'), ('auth.device.registered', 'Device Registered'), ('auth.device.invalidated', 'Device Invalidated'), ('user.created', 'User Created'), ('user.updated', 'User Updated'), ('user.revoked', 'User Revoked'), ('user.suspended', 'User Suspended'), ('user.restored', 'User Restored'), ('invite.created', 'Invite Created'), ('invite.used', 'Invite Used'), ('invite.expired', 'Invite Expired'), ('report.created', 'Report Created'), ('report.viewed', 'Report Viewed'), ('report.assigned', 'Report Assigned'), ('report.status.changed', 'Report Status Changed'), ('report.validated', 'Report Validated'), ('report.rejected', 'Report Rejected'), ('media.uploaded', 'Media Uploaded'), ('media.accessed', 'Media Accessed'), ('media.decrypted', 'Media Decrypted'), ('escalation.created', 'Escalation Created'), ('escalation.approved', 'Escalation Approved'), ('escalation.rejected', 'Escalation Rejected'), ('identity.reveal.requested', 'Identity Reveal Requested'), ('identity.reveal.approved', 'Identity Reveal Approved'), ('identity.reveal.rejected', 'Identity Reveal Rejected'), ('identity.revealed', 'Identity Revealed'), ('decryption.requested', 'Decryption Requested'), ('decryption.approved', 'Decryption Approved'), ('decryption.rejected', 'Decryption Rejected'), ('decryption.performed', 'Decryption Performed'), ('system.error', 'System Error'), ('system.security.alert', 'Security Alert')], db_index=True, help_text='Type of event being logged', max_length=50)),
                ('severity', models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], db_index=True, default='info', help_text='Severity level of the event', max_length=10)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the event occurred')),
                ('actor_id', models.CharField(blank=True, db_index=True, help_text='UUID of user who performed action (as string for immutability)', max_length=36)),
                ('actor_role', models.CharField(blank=True, help_text='Role of actor at time of action', max_length=20)),
                ('actor_identifier', models.CharField(blank=True, help_text='Identifier of actor (anonymized for JanMitra)', max_length=255)),
                ('target_type', models.CharField(blank=True, help_text='Type of entity being acted upon', max_length=50)),
                ('target_id', models.CharField(blank=True, db_index=True, help_text='UUID of target entity (as string)', max_length=36)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP address', null=True)),
                ('user_agent', models.CharField(blank=True, help_text='Client user agent string', max_length=500)),
                ('device_fingerprint_hash', models.CharField(blank=True, help_text='Hashed device fingerprint', max_length=64)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method', max_length=10)),
                ('request_path', models.CharField(blank=True, help_text='API endpoint path', max_length=500)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of event')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data about the event')),
                ('success', models.BooleanField(default=True, help_text='Whether the action was successful')),
                ('error_message', models.TextField(blank=True, help_text='Error message if action failed')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='audit_logs_event_t_222f56_idx'), models.Index(fields=['actor_id', 'timestamp'], name='audit_logs_actor_i_ce2144_idx'), models.Index(fields=['target_id', 'timestamp'], name='audit_logs_target__b24073_idx'), models.Index(fields=['severity', 'timestamp'], name='audit_logs_severit_549d29_idx')],
            },
        ),
    ]
