# Generated by Django 5.1 on 2026-01-28 12:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_dde14f_idx',
            old_name='notificatio_recipie_7d7c8d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_2d3764_idx',
            old_name='notificatio_recipie_b3e9e0_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_notific_498289_idx',
            old_name='notificatio_notific_e5c2ab_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated'),
        ),
    ]
