# Generated by Django 4.2.27 on 2026-02-07 10:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('latest_version', models.CharField(help_text="Latest version string (e.g., '1.2.3')", max_length=20)),
                ('minimum_supported_version', models.CharField(help_text='Minimum version required to use the app. App will force update if older.', max_length=20)),
                ('apk_file', models.FileField(blank=True, help_text='APK file for download', null=True, upload_to='app_updates/')),
                ('is_active', models.BooleanField(default=True, help_text='Only the active version is returned by the API')),
            ],
            options={
                'verbose_name': 'App Version',
                'verbose_name_plural': 'App Versions',
                'db_table': 'app_versions',
                'ordering': ['-created_at'],
            },
        ),
    ]
