# Generated by Django 5.1 on 2026-04-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policestation',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Full station address'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='jurisdiction_areas',
            field=models.TextField(blank=True, default='', help_text='Comma-separated area/locality names this station covers'),
        ),
        migrations.AddField(
            model_name='policestation',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Station contact number', max_length=20),
        ),
        migrations.AddField(
            model_name='policestation',
            name='zone',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Police zone (e.g., Zone-1 East)', max_length=50),
        ),
        migrations.AlterField(
            model_name='policestation',
            name='code',
            field=models.CharField(db_index=True, help_text='Unique station code (e.g., PS-GJ-AHM-001)', max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='policestation',
            index=models.Index(fields=['zone'], name='station_zone_idx'),
        ),
    ]
