# Generated by Django 5.1 on 2026-04-15 11:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersionConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4)', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - records are never physically deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft-deleted', null=True)),
                ('latest_version', models.CharField(help_text='Latest app version string (e.g., 1.2.0)', max_length=20)),
                ('force_update', models.BooleanField(default=False, help_text='If True, users on older versions are blocked until they update')),
                ('apk_url', models.URLField(blank=True, default='', help_text='Direct download URL for the latest APK', max_length=500)),
                ('release_notes', models.TextField(blank=True, default='', help_text="What's new in this version (shown to users)")),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only the active config is served to clients')),
            ],
            options={
                'verbose_name': 'App Version Config',
                'verbose_name_plural': 'App Version Configs',
                'db_table': 'app_version_config',
                'ordering': ['-created_at'],
            },
        ),
    ]
